name: 'GitHub Actions Subscribe'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 21 * * *'
jobs:
  Subscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 350
        run: python main.py ${{ secrets.HOST }} ${{ secrets.KEY1 }} ${{ secrets.KEY2 }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "✈ Update Subscribe"
      - name: 'Push Changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}